version: "3.8"

services:
  maawf_frontend:
    image: maawf_frontend
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - API_DOMAIN=api.maawf.tech
    ports:
      - "3000:80"