name: Ci/CD Pipeline

env:
  APP_NAME: "maaawf_frontend"
  TAG: ${{ github.sha }}

on:
  push:
    branches: ['dev', 'test', 'prod']
  pull_request:
    branches: ['dev']

jobs:
  build-push:
    name: "Build and Push to Docker Hub"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.APP_NAME }}:${{ env.TAG }}
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.APP_NAME }}:latest

  deploy:
    if: github.event_name == 'pull_request'
    name: Trigger deployment
    needs: build-push
    runs-on: ubuntu-latest

    steps:
      - name: Trigger deploy workflow
        uses: convictional/trigger-workflow-and-wait@v1.6.5
        with:
          owner: ${{ github.repository_owner }}
          repo: maawf_backend
          github_token: ${{ secrets.PERSONAL_GITHUB_ACCESS_TOKEN }}
          workflow_file_name: deploy.yaml
          ref: ${{ github.ref }}
          wait_interval: 10
          propagate_failure: true
          trigger_workflow: true
          wait_workflow: true
