name: Ci/CD Pipeline

env:
  APP_NAME: "maaawf_frontend"
  TAG: ${{ github.sha }}

on:
  push:
    branches: ["dev"]
  pull_request:
    branches: ["dev"]

jobs:
  build-push:
    name: "Build and Push to Docker Hub"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.APP_NAME }}:${{ env.TAG }}
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.APP_NAME }}:latest

  deploy:
    name: "Trigger deployment"
    needs: build-push
    runs-on: ubuntu-latest

    steps:
      - if: github.event_name == 'pull_request'
        run: exit 0

      - name: Trigger deploy workflow of backend
        uses: convictional/trigger-workflow-and-wait@v1.6.1
        with:
          owner: ${{ github.repository_owner }}
          repo: maaawf_backend
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow_file_name: deploy.yml
          ref: dev
          wait_interval: 10
          propagate_failure: true
          trigger_worflow: true
          wait_workflow: true
